[build]
  base = "movie-challenge"
  publish = "dist"
  functions = ".netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
